version: '3'

services:
 myapp:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5004"
   ports:
     - "5004:5004"

 db:
    image: postgres:15.4-alpine3.18
    env_file:
      - .env
    ports:
      - "5432:5432"